export const UI_TYPES = {
	SHOW_DRAWER: 'SHOW_DRAWER',
	HIDE_DRAWER: 'HIDE_DRAWER',
	SHOW_MODAL: 'SHOW_MODAL',
	HIDE_MODAL: 'HIDE_MODAL',
	SHOW_MODAL_FORM: 'SHOW_MODAL_FORM',
	HIDE_MODAL_FORM: 'HIDE_MODAL_FORM',
};
