import { Inter } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import GlobalProvider from '@/context/global/GlobalContext';
import OcProvider from '@/context/OC/OcContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<OcProvider>
				<GlobalProvider>
					<body className={inter.className}>
						<AntdRegistry>{children}</AntdRegistry>
					</body>
				</GlobalProvider>
			</OcProvider>
		</html>
	);
}
