export const ocDataDb = [
	{
		id: '1',
		oc_number: 'OC-331-5',
		name: 'Palos',
		gloss: 'Palos para subnivel',
		supplier_rut: '77.930.430-1',
		supplier_name: 'Sodimac Homecenter S.A',
		supplier: 'Sodimac Homecenter S.A',
		delivery_date: '2024-08-20T05:00:00.000Z',
		delivery_address: 'Las rosas 50, Vitacura, Región Metropolitana',
		currency_type: 'Peso',
		items: [
			{
				sku: 'PAN3CA1UN',
				item: 'Palos',
				description: 'Palos N 3',
				gloss: 'Palos N 3',
				cost_account: 'cost_account_1',
				measurement_unit: 'un',
				quantity: 20,
				subtotal: 119800,
				unit_price: 5990,
				received_amount: 0,
				amount_to_receive: 119800,
				receipt_status: 'Sin recepción',
			},
			{
				sku: 'PAN4CA1UN',
				item: 'Palos',
				description: 'Palos N 4',
				gloss: 'Palos N 4',
				cost_account: 'cost_account_1',
				measurement_unit: 'un',
				quantity: 2,
				subtotal: 11980,
				unit_price: 5990,
				received_amount: 0,
				amount_to_receive: 11980,
				receipt_status: 'Sin recepción',
			},
		],
		net_total: 131780,
		iva: 25038.2,
		total: 156818.2,
		creation_date: '06/08/24',
		approval_date: '--',
		oc_status: 'Borrador',
		reception_date: '06/08/24',
	},
	{
		id: '2',
		oc_number: 'OC-332-3',
		name: 'Varillas',
		gloss: 'Varillas para subnivel',
		supplier_rut: '77.930.430-1',
		supplier_name: 'Sodimac Homecenter S.A',
		supplier: 'Sodimac Homecenter S.A',
		delivery_date: '2024-08-20T05:00:00.000Z',
		delivery_address: 'Las rosas 50, Vitacura, Región Metropolitana',
		currency_type: 'Peso',
		items: [
			{
				sku: 'VAN1CA1UN',
				item: 'Varillas',
				description: 'Varillas N 1',
				gloss: 'Varillas N 1',
				cost_account: 'cost_account_1',
				measurement_unit: 'un',
				quantity: 40,
				subtotal: 1839600,
				unit_price: 45990,
				received_amount: 1839600,
				amount_to_receive: 1839600,
				receipt_status: 'Recepción con factura',
			},
		],
		net_total: 1839600,
		iva: 349524,
		total: 2189124,
		creation_date: '15/05/24',
		approval_date: '20/05/24',
		oc_status: 'Aprobada',
	},
	{
		id: '3',
		oc_number: 'OC-335-7',
		name: 'Pintura',
		gloss: 'Pintura',
		supplier_rut: '55.358.387-1',
		supplier_name: 'Proveedor Pintura',
		supplier: 'Proveedor Pintura',
		delivery_date: '2024-08-20T05:00:00.000Z',
		delivery_address: 'Las rosas 50, Vitacura, Región Metropolitana',
		currency_type: 'Peso',
		items: [
			{
				sku: 'PIN1CA2UN',
				item: 'Pintura',
				description: 'Pintura N 1',
				gloss: 'Pintura N 1',
				cost_account: 'cost_account_2',
				measurement_unit: 'un',
				quantity: 12,
				subtotal: 840000,
				unit_price: 70000,
				received_amount: 700000,
				amount_to_receive: 840000,
				receipt_status: 'Recepción sin factura',
			},
		],
		net_total: 840000,
		iva: 159600,
		total: 999600,
		creation_date: '12/02/24',
		approval_date: '--',
		oc_status: 'Rechazada',
	},
	{
		id: '4',
		oc_number: 'OC-340-0',
		name: 'Tornillos',
		gloss: 'Tornillos',
		supplier_rut: '55.358.387-1',
		supplier_name: 'Proveedor Tornillos',
		supplier: 'Proveedor Tornillos',
		delivery_date: '2024-08-20T05:00:00.000Z',
		delivery_address: 'Las rosas 50, Vitacura, Región Metropolitana',
		currency_type: 'Peso',
		items: [
			{
				sku: 'TON1CA1UN',
				item: 'Tornillos',
				description: 'Tornillos N 1',
				gloss: 'Tornillos N 1',
				cost_account: 'cost_account_1',
				measurement_unit: 'un',
				quantity: 120,
				subtotal: 180000,
				unit_price: 1500,
				received_amount: 180000,
				amount_to_receive: 180000,
				receipt_status: 'Recepción con factura',
			},
			{
				sku: 'TON2CA1UN',
				item: 'Tornillos',
				description: 'Tornillos N 2',
				gloss: 'Tornillos N 2',
				cost_account: 'cost_account_1',
				measurement_unit: 'un',
				quantity: 80,
				subtotal: 96000,
				unit_price: 1200,
				received_amount: 0,
				amount_to_receive: 96000,
				receipt_status: 'Anulada',
			},
		],
		net_total: 276000,
		iva: 52440,
		total: 328440,
		creation_date: '09/02/24',
		approval_date: '--',
		oc_status: 'En revisión',
	},
];

export const approvalEventsDb = [
	{
		event_id: 'e3323',
		oc_id: '2',
		aprobador: 'creador',
		event_date: '15/05/24',
		event_status: 'Envío a aprobación',
	},
	{
		event_id: 'e3323',
		oc_id: '2',
		aprobador: 'aprobador5',
		event_date: '15/05/24',
		event_status: 'Aprobada',
	},
	{
		event_id: 'e3357',
		oc_id: '3',
		aprobador: 'creador',
		event_date: '12/02/24',
		event_status: 'Envío a aprobación',
	},
	{
		event_id: 'e3357',
		oc_id: '3',
		aprobador: 'aprobador5',
		event_date: '14/02/24',
		event_status: 'Rechazada',
	},
	{
		event_id: 'e3400',
		oc_id: '4',
		aprobador: 'creador',
		event_date: '12/02/24',
		event_status: 'Envío a aprobación',
	},
];

export const receiptsData = [
	{
		id: '1',
		oc_number: 'OC-331-5',
		oc_name: 'Palos',
		oc_gloss: 'Palos para subnivel',
		provider_rut: '77.930.430-1',
		provider_name: 'Sodimac Homecenter S.A',
		provider: 'Sodimac Homecenter S.A',
		code: '3315',
		description: 'Palos para subnivel',
		currency_type: 'Peso',
		oc_amount: 276000,
		received_quantity: 20,
		received_amount: 0,
		creation_date: '06/08/24',
		reception_date: '07/08/24',
		doc_type: 'Guía despacho',
		doc_number: '123',
		sku: 'PAN3CA1UN',
		receipt_status: 'Sin recepción',
		invoice_number: '34',
	},
	{
		id: '2',
		oc_number: 'OC-332-3',
		oc_name: 'Varillas',
		oc_gloss: 'Varillas para subnivel',
		provider_rut: '77.930.430-1',
		provider_name: 'Sodimac Homecenter S.A',
		provider: 'Sodimac Homecenter S.A',
		code: '3323',
		description: 'Varillas para subnivel',
		currency_type: 'Peso',
		oc_amount: 1839600,
		received_quantity: 40,
		received_amount: 1839600,
		creation_date: '15/05/24',
		reception_date: '17/05/24',
		doc_type: 'Guía despacho',
		doc_number: '234',
		sku: 'VAN1CA1UN',
		receipt_status: 'Recepción con factura',
		invoice_number: '25',
	},
	{
		id: '3',
		oc_number: 'OC-335-7',
		oc_name: 'Pintura',
		oc_gloss: 'Pintura',
		provider_rut: '55.358.387-1',
		provider_name: 'Proveedor Pintura',
		provider: 'Proveedor Pintura',
		code: '3357',
		description: 'Descripción para pintura',
		currency_type: 'Peso',
		oc_amount: 840000,
		received_quantity: 10,
		received_amount: 700000,
		creation_date: '12/02/24',
		reception_date: '17/05/24',
		doc_type: 'Guía despacho',
		doc_number: '456',
		sku: 'PIN1CA2UN',
		receipt_status: 'Recepción sin factura',
		invoice_number: '22',
	},
	{
		id: '4',
		oc_number: 'OC-340-0',
		oc_name: 'Tornillos',
		oc_gloss: 'Tornillos',
		provider_rut: '55.358.387-1',
		provider_name: 'Proveedor Tornillos',
		provider: 'Proveedor Tornillos',
		code: '3357',
		description: 'Descripción para tornillos',
		currency_type: 'Peso',
		oc_amount: 180000,
		received_quantity: 120,
		received_amount: 180000,
		creation_date: '09/02/24',
		reception_date: '11/02/24',
		doc_type: 'Guía despacho',
		doc_number: '765',
		sku: 'TON1CA1UN',
		receipt_status: 'Recepción con factura',
		invoice_number: '18',
	},
	{
		id: '5',
		oc_number: 'OC-331-5',
		oc_name: 'Palos',
		oc_gloss: 'Palos para subnivel',
		provider_rut: '77.930.430-1',
		provider_name: 'Sodimac Homecenter S.A',
		provider: 'Sodimac Homecenter S.A',
		code: '3315',
		description: 'Palos para subnivel',
		currency_type: 'Peso',
		oc_amount: 276000,
		received_quantity: 2,
		received_amount: 0,
		creation_date: '06/08/24',
		reception_date: '07/08/24',
		doc_type: 'Guía despacho',
		doc_number: '345',
		sku: 'PAN4CA1UN',
		receipt_status: 'Sin recepción',
		invoice_number: '39',
	},
	{
		id: '6',
		oc_number: 'OC-340-0',
		oc_name: 'Tornillos',
		oc_gloss: 'Tornillos',
		provider_rut: '55.358.387-1',
		provider_name: 'Proveedor Tornillos',
		provider: 'Proveedor Tornillos',
		code: '3357',
		description: 'Descripción para tornillos',
		currency_type: 'Peso',
		oc_amount: 96000,
		received_quantity: 80,
		received_amount: 0,
		creation_date: '09/02/24',
		reception_date: '11/02/24',
		doc_type: 'Guía despacho',
		doc_number: '765',
		sku: 'TON1CA1UN',
		receipt_status: 'Anulada',
		invoice_number: '18',
	},
];

export const OCS = [];
