export const PO_TYPES = {
	GET_ALL_PURCHASE_ORDERS: 'GET_ALL_PURCHASE_ORDERS',
	GET_ONE_PURCHASE_ORDER: 'GET_ONE_PURCHASE_ORDER',
	GET_PURCHASE_ORDER_TO_RECEIVE: 'GET_PURCHASE_ORDER_TO_RECEIVE',
	UPDATE_PURCHASE_ORDER: 'UPDATE_PURCHASE_ORDER',
	DELETE_PURCHASE_ORDER: 'DELETE_PURCHASE_ORDER',
	GET_ALL_GENERAL_ITEMS: 'GET_ALL_GENERAL_ITEMS',
	CREATE_GENERAL_ITEM: 'CREATE_GENERAL_ITEM',
};
